version: '2'
services:
  mysql:
    image: openzipkin/zipkin-mysql
    ports:
      - "3306:3306"
    networks:
      - opentracing
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      - "9411:9411"
    networks:
      - opentracing
    depends_on:
      - mysql
  esb:
    image: serrodcal/opentracing-esb
    build: ./esb
    ports:
      - "19444:19444"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    networks:
      - opentracing
    depends_on:
      - mysql
      - zipkin
networks:
  opentracing:
    driver: bridge
